version: '3'

services: 
  
  server-gui:
    container_name: iai2-oven-node-gui
    restart: always
    build: .
    ports:
      - '5000:80'
    links: 
      - mongo
    environment: 
      - PORT=5000
  